name: magjob frontend CI with NodeJS and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarcloud-scan-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy-to-registry-frontend:
    needs: [ sonarcloud-scan-frontend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
         node-version: 21
      - name: Install dependencies with npm
        run: npm install
      - name: Test with npm
        run: npm test
      - name: Build with npm
        run: npm run build
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: keepitup2023/magjob-frontend:latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  update-config-repository:
    needs: [ build-and-deploy-to-registry-backend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and run deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            wget "https://raw.githubusercontent.com/KeepIt-Up/MagJob/main/deploy.sh" -O deploy.sh
            chmod 777 deploy.sh
            ./deploy.sh
